"""Draw Sonolin's icon: a speaker cone seen from the front, on a near-black soft square.

    python3 tools/make_icon.py

A white ring and a centre dot, the driver of a speaker. The tile is a true
superellipse (the soft square of current app icons, which a rounded rectangle
only approximates), computed rather than drawn by hand. Writes both copies:
`sonolin/gui/sonolin.svg`, which the app and its menu entry use, and
`data/icons/sonolin.svg` for packagers.

Two flat colours and nothing else: no gradients, no shadows (KDE draws icons
with QtSvg, which ignores filters anyway).
"""

from __future__ import annotations

import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGETS = (ROOT / "sonolin" / "gui" / "sonolin.svg", ROOT / "data" / "icons" / "sonolin.svg")

TILE = "#111317"
MARK = "#ffffff"


def squircle(cx: float, cy: float, half: float, n: float = 5.0, steps: int = 96) -> str:
    """|x|^n + |y|^n = half^n, as a closed path."""
    points = []
    for i in range(steps):
        t = 2 * math.pi * i / steps
        c, s = math.cos(t), math.sin(t)
        points.append(f"{cx + half * math.copysign(abs(c) ** (2 / n), c):.2f} "
                      f"{cy + half * math.copysign(abs(s) ** (2 / n), s):.2f}")
    return "M" + "L".join(points) + "Z"


def icon() -> str:
    tile = squircle(128, 128, 116)
    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="256" height="256" viewBox="0 0 256 256">
  <title>Sonolin</title>
  <!-- Generated by tools/make_icon.py; edit that, not this. -->
  <path d="{tile}" fill="{TILE}"/>
  <circle cx="128" cy="128" r="58" fill="none" stroke="{MARK}" stroke-width="18"/>
  <circle cx="128" cy="128" r="17" fill="{MARK}"/>
</svg>
"""


def main() -> None:
    svg = icon()
    for target in TARGETS:
        target.write_text(svg, encoding="utf-8")
        print(f"wrote {target.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
